# To use the same mirroring approach in a new repo, copy 'ci' directory and aviator.yml,
# then replace references to Github repo in:
# - resources.yml
# - aviator.yml
# - jobs/mirror-job.yml

jobs:
  - name: mirror-emr-encryption-materials-provider
    plan:
      - get: aws-management-infrastructure
      - get: emr-encryption-materials-provider
        trigger: true
        params:
          globs:
            - "*all.jar"
      - .: (( inject meta.plan.terraform-output ))
      - task: mirror-emr-encryption-materials-provider
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_awscli_repository))
              version: ((dataworks.docker_awscli_version))
              tag: ((dataworks.docker_awscli_version))
          inputs:
            - name: bucket_name
            - name: emr-encryption-materials-provider
          params:
            ARTEFACT_DIR: "emr-encryption-materials-provider"
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
            AWS_REGION: ((dataworks.aws_region))
            AWS_DEFAULT_REGION: ((dataworks.aws_region))
          run:
            path: sh
            args:
              - -exc
              - |
                source /assume-role
                set +x
                export BUCKET=`cat bucket_name/bucket_name`
                aws s3 cp ${ARTEFACT_DIR}/*.jar s3://${BUCKET}/${ARTEFACT_DIR}/encryption-materials-provider-all.jar
                export VERSION=`echo ${ARTEFACT_DIR}/encryption-materials-provider*.jar | sed "s/^${ARTEFACT_DIR}\/encryption-materials-provider-\(.*\)-all.jar$/\1/"`
                export VERSION_NUMBER="\"${VERSION}\""
                echo $VERSION_NUMBER
                export TAG="{\"TagSet\":[{\"Key\":\"version\",\"Value\":${VERSION_NUMBER}}]}"
                aws s3api put-object-tagging \
                --bucket ${BUCKET} \
                --key ${ARTEFACT_DIR}/encryption-materials-provider-all.jar \
                --tagging $TAG
