# To use the same mirroring approach in a new repo, copy 'ci' directory and aviator.yml,
# then replace references to Github repo in:
# - resources.yml
# - aviator.yml
# - jobs/mirror-job.yml

jobs:
  - name: mirror-emr-encryption-materials-provider
    plan:
      - get: aws-management-infrastructure
      - get: emr-encryption-materials-provider
        trigger: true
        params:
          globs:
            - "*all.jar"
      - .: (( inject meta.plan.terraform-output ))
      - .: (( inject meta.plan.create-aws-profiles ))
      - task: mirror-emr-encryption-materials-provider
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-awscli.repository))
              version: ((docker-awscli.version))
              tag: ((docker-awscli.version))
          inputs:
            - name: bucket_name
            - name: .aws
            - name: emr-encryption-materials-provider
          params:
            AWS_PROFILE: ci
            AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
            AWS_CONFIG_FILE: .aws/config
            ARTEFACT_DIR: "emr-encryption-materials-provider"
          run:
            path: sh
            args:
              - -exc
              - |
                AWS_SHARED_CREDENTIALS_FILE="${PWD}/${AWS_SHARED_CREDENTIALS_FILE}"
                AWS_CONFIG_FILE="${PWD}/${AWS_CONFIG_FILE}"
                export BUCKET=`cat bucket_name/bucket_name`
                aws s3 cp ${ARTEFACT_DIR}/*.jar s3://${BUCKET}/${ARTEFACT_DIR}/encryption-materials-provider-all.jar
                VERSION=`echo ${ARTEFACT_DIR}/encryption-materials-provider*.jar | sed "s/^${ARTEFACT_DIR}\/encryption-materials-provider-\(.*\)-all.jar$/\1/"`
                aws s3api put-object-tagging \
                --bucket ${BUCKET} \
                --key ${ARTEFACT_DIR}/encryption-materials-provider-all.jar \
                --tagging '{"TagSet": [
                { "Key": "version", "Value": $VERSION }
                ]}'

