name: 'Pull Request'
on:
  pull_request:
    branches:
      - master

jobs:
  pull_request:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: ./gradlew clean build

      - name: snyk-scan
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=dwp-dataworks --severity-threshold=high
