name: 'Pull Request'
on:
  pull_request:
    branches:
      - master

jobs:
  pull_request:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: ./gradlew clean build

